/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controllers.CtrlCaixa;
import controllers.CtrlRelatorios;
import excecoes.ExcecaoGenerica;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import modelo.Caixa;
import net.sf.jasperreports.view.JasperViewer;
import utilitarios.UsuariosUtil;

/**
 *
 * @author Gabriel
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private Info                    INFO                        = null;
    private FrmCaixa                FRM_CAIXA                   = null;
    private FrmVendas               FRM_VENDAS                  = null;
    private FrmCompras              FRM_COMPRAS                 = null;
    private FrmCadCargo             FRM_CAD_CARGO               = null;
    private FrmCadCidades           FRM_CAD_CIDADE              = null;
    private FrmCadEstado            FRM_CAD_ESTADO              = null;
    private FrmRelVendas            FRM_REL_VENDAS              = null;
    private FrmRelCompras           FRM_REL_COMPRAS             = null;
    private FrmCadProduto           FRM_CAD_PRODUTO             = null;
    private FrmCadCliente           FRM_CAD_CLIENTE             = null;
    private FrmCadUsuario           FRM_CAD_USUARIO             = null;
    private FrmCadCategoria         FRM_CAD_CATEGORIA           = null;
    private FrmCadComissoes         FRM_CAD_COMISSOES           = null;       
    private FrmCadFornecedor        FRM_CAD_FORNECEDOR          = null;
    private FrmCadFuncionario       FRM_CAD_FUNCIONARIO         = null;
    private FrmVisualizarVendas     FRM_VISUALIZAR_VENDAS       = null;
    private FrmCadTipoPagamento     FRM_CAD_TIPO_PAGAMENTO      = null;    
    private FrmVisualizarCompras    FRM_VISUALIZAR_COMPRAS      = null;
    private FrmCadCondicaoPagamento FRM_CAD_CONDICAO_PAGAMENTO  = null;
    
    
    private Timer TIMER;
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        lblUsuario.setText(UsuariosUtil.getUsuario().getLogin());
        TIMER = new Timer();
        TimerTask tk = new TimerTask() {
            @Override
            public void run() {
                lblTime.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date()));
            }
        };
        TIMER.schedule(tk, 0, 1000);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBody = new javax.swing.JPanel();
        imgPrincipalCenter = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        menuSuperior = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        subMenuCadastroClientes = new javax.swing.JMenuItem();
        subMenuCadastroFornecedores = new javax.swing.JMenuItem();
        subMenuCadastroUsuarios = new javax.swing.JMenuItem();
        subMenuCadastroCidades = new javax.swing.JMenuItem();
        subMenuCadastroEstados = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        subMenuCadastrosFinanceiros = new javax.swing.JMenu();
        subMenuCadastroComissoes = new javax.swing.JMenuItem();
        subMenuCadastroTiposPagamentos = new javax.swing.JMenuItem();
        subMenuCadastroCondicoesPagamentos = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenu();
        subMenuCadastroCargos = new javax.swing.JMenuItem();
        subMenuCadastroFuncionarios = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        subMenuCategorias = new javax.swing.JMenuItem();
        subMenuProdutos = new javax.swing.JMenuItem();
        menuMovimentacoes = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenu();
        subMenuVendas = new javax.swing.JMenuItem();
        subMenuVisualizarVendas = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        subMenuCompras = new javax.swing.JMenuItem();
        subMenuVisualizarCompras = new javax.swing.JMenuItem();
        subMenuCaixa = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelClientes = new javax.swing.JMenu();
        subMenuRelatorioClientesFisicosAtivos = new javax.swing.JMenuItem();
        subMenuRelatorioClientesJuridicosAtivos = new javax.swing.JMenuItem();
        subMenuRelatorioFuncionariosAtivos = new javax.swing.JMenuItem();
        subMenuRelatoriosFornecedores = new javax.swing.JMenuItem();
        menuRelProdutos = new javax.swing.JMenu();
        subMenuRelatorioProdutosAtivos = new javax.swing.JMenuItem();
        subMenuRelatorioEstoqueProdutos = new javax.swing.JMenuItem();
        subMenuRelatorioVendas = new javax.swing.JMenuItem();
        subMenuRelatorioCompras = new javax.swing.JMenuItem();
        menuRelCaixa = new javax.swing.JMenu();
        subMenuRelatorioCaixa = new javax.swing.JMenuItem();
        subMenuRelatorioFechamentosCaixas = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Control Manager");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelBody.setBackground(new java.awt.Color(102, 153, 255));

        imgPrincipalCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPrincipalCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-emporio-cardoso.png"))); // NOI18N

        panelFooter.setBackground(new java.awt.Color(255, 255, 255));
        panelFooter.setMinimumSize(new java.awt.Dimension(0, 48));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuario.setText("USUARIO_LOGIN");

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTime.setText("dd/MM/yyyy hh:MM");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addContainerGap(1048, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addGap(65, 65, 65)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblTime))
                .addContainerGap())
        );

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-sistema-150-75.png"))); // NOI18N

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLogo)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                .addComponent(imgPrincipalCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgPrincipalCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuSuperior.setBackground(new java.awt.Color(255, 255, 255));

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/application_add.png"))); // NOI18N
        menuCadastros.setText("Cadastros");

        subMenuCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_green.png"))); // NOI18N
        subMenuCadastroClientes.setText("Clientes");
        subMenuCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(subMenuCadastroClientes);

        subMenuCadastroFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_gray.png"))); // NOI18N
        subMenuCadastroFornecedores.setText("Fornecedores");
        subMenuCadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroFornecedoresActionPerformed(evt);
            }
        });
        menuCadastros.add(subMenuCadastroFornecedores);

        subMenuCadastroUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        subMenuCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_orange.png"))); // NOI18N
        subMenuCadastroUsuarios.setText("Usuários");
        subMenuCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroUsuariosActionPerformed(evt);
            }
        });
        menuCadastros.add(subMenuCadastroUsuarios);

        subMenuCadastroCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/building.png"))); // NOI18N
        subMenuCadastroCidades.setText("Cidades");
        subMenuCadastroCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroCidadesActionPerformed(evt);
            }
        });
        menuCadastros.add(subMenuCadastroCidades);

        subMenuCadastroEstados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/building.png"))); // NOI18N
        subMenuCadastroEstados.setText("Estados");
        subMenuCadastroEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroEstadosActionPerformed(evt);
            }
        });
        menuCadastros.add(subMenuCadastroEstados);

        menuSuperior.add(menuCadastros);

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro");

        subMenuCadastrosFinanceiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/application_add.png"))); // NOI18N
        subMenuCadastrosFinanceiros.setText("Cadastros");

        subMenuCadastroComissoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money_dollar.png"))); // NOI18N
        subMenuCadastroComissoes.setText("Comissões");
        subMenuCadastroComissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroComissoesActionPerformed(evt);
            }
        });
        subMenuCadastrosFinanceiros.add(subMenuCadastroComissoes);

        subMenuCadastroTiposPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money_dollar.png"))); // NOI18N
        subMenuCadastroTiposPagamentos.setText("Tipos de Pagamentos");
        subMenuCadastroTiposPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroTiposPagamentosActionPerformed(evt);
            }
        });
        subMenuCadastrosFinanceiros.add(subMenuCadastroTiposPagamentos);

        subMenuCadastroCondicoesPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money_dollar.png"))); // NOI18N
        subMenuCadastroCondicoesPagamentos.setText("Condições de Pagamentos");
        subMenuCadastroCondicoesPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroCondicoesPagamentosActionPerformed(evt);
            }
        });
        subMenuCadastrosFinanceiros.add(subMenuCadastroCondicoesPagamentos);

        menuFinanceiro.add(subMenuCadastrosFinanceiros);

        menuSuperior.add(menuFinanceiro);

        menuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_suit.png"))); // NOI18N
        menuFuncionarios.setText("Funcionários");

        subMenuCadastroCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/vcard.png"))); // NOI18N
        subMenuCadastroCargos.setText("Cargos");
        subMenuCadastroCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroCargosActionPerformed(evt);
            }
        });
        menuFuncionarios.add(subMenuCadastroCargos);

        subMenuCadastroFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_suit.png"))); // NOI18N
        subMenuCadastroFuncionarios.setText("Funcionários");
        subMenuCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCadastroFuncionariosActionPerformed(evt);
            }
        });
        menuFuncionarios.add(subMenuCadastroFuncionarios);

        menuSuperior.add(menuFuncionarios);

        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/box.png"))); // NOI18N
        menuProdutos.setText("Produtos");

        subMenuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/layers.png"))); // NOI18N
        subMenuCategorias.setText("Categorias");
        subMenuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCategoriasActionPerformed(evt);
            }
        });
        menuProdutos.add(subMenuCategorias);

        subMenuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/package.png"))); // NOI18N
        subMenuProdutos.setText("Produto");
        subMenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuProdutosActionPerformed(evt);
            }
        });
        menuProdutos.add(subMenuProdutos);

        menuSuperior.add(menuProdutos);

        menuMovimentacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/basket.png"))); // NOI18N
        menuMovimentacoes.setText("Movimentações");

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/cart.png"))); // NOI18N
        menuVendas.setText("Vendas");

        subMenuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/basket_go.png"))); // NOI18N
        subMenuVendas.setText("Nova Venda");
        subMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuVendasActionPerformed(evt);
            }
        });
        menuVendas.add(subMenuVendas);

        subMenuVisualizarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/magnifier.png"))); // NOI18N
        subMenuVisualizarVendas.setText("Visualizar Vendas");
        subMenuVisualizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuVisualizarVendasActionPerformed(evt);
            }
        });
        menuVendas.add(subMenuVisualizarVendas);

        menuMovimentacoes.add(menuVendas);

        menuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/cart.png"))); // NOI18N
        menuCompras.setText("Compras");

        subMenuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/basket_go.png"))); // NOI18N
        subMenuCompras.setText("Nova Compra");
        subMenuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuComprasActionPerformed(evt);
            }
        });
        menuCompras.add(subMenuCompras);

        subMenuVisualizarCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/magnifier.png"))); // NOI18N
        subMenuVisualizarCompras.setText("Visualizar Compras");
        subMenuVisualizarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuVisualizarComprasActionPerformed(evt);
            }
        });
        menuCompras.add(subMenuVisualizarCompras);

        menuMovimentacoes.add(menuCompras);

        subMenuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money_dollar.png"))); // NOI18N
        subMenuCaixa.setText("Caixa");
        subMenuCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCaixaActionPerformed(evt);
            }
        });
        menuMovimentacoes.add(subMenuCaixa);

        menuSuperior.add(menuMovimentacoes);

        menuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/report.png"))); // NOI18N
        menuRelatorio.setText("Relatórios");

        menuRelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_green.png"))); // NOI18N
        menuRelClientes.setText("Clientes");

        subMenuRelatorioClientesFisicosAtivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_green.png"))); // NOI18N
        subMenuRelatorioClientesFisicosAtivos.setText("Clientes Físicos");
        subMenuRelatorioClientesFisicosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioClientesFisicosAtivosActionPerformed(evt);
            }
        });
        menuRelClientes.add(subMenuRelatorioClientesFisicosAtivos);

        subMenuRelatorioClientesJuridicosAtivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_green.png"))); // NOI18N
        subMenuRelatorioClientesJuridicosAtivos.setText("Clientes Jurídicos");
        subMenuRelatorioClientesJuridicosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioClientesJuridicosAtivosActionPerformed(evt);
            }
        });
        menuRelClientes.add(subMenuRelatorioClientesJuridicosAtivos);

        menuRelatorio.add(menuRelClientes);

        subMenuRelatorioFuncionariosAtivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_suit.png"))); // NOI18N
        subMenuRelatorioFuncionariosAtivos.setText("Funcionários");
        subMenuRelatorioFuncionariosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioFuncionariosAtivosActionPerformed(evt);
            }
        });
        menuRelatorio.add(subMenuRelatorioFuncionariosAtivos);

        subMenuRelatoriosFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/user_gray.png"))); // NOI18N
        subMenuRelatoriosFornecedores.setText("Fornecedores");
        subMenuRelatoriosFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatoriosFornecedoresActionPerformed(evt);
            }
        });
        menuRelatorio.add(subMenuRelatoriosFornecedores);

        menuRelProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/box.png"))); // NOI18N
        menuRelProdutos.setText("Produtos");

        subMenuRelatorioProdutosAtivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/box.png"))); // NOI18N
        subMenuRelatorioProdutosAtivos.setText("Produtos Ativos");
        subMenuRelatorioProdutosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioProdutosAtivosActionPerformed(evt);
            }
        });
        menuRelProdutos.add(subMenuRelatorioProdutosAtivos);

        subMenuRelatorioEstoqueProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/box.png"))); // NOI18N
        subMenuRelatorioEstoqueProdutos.setText("Estoque de Produtos");
        subMenuRelatorioEstoqueProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioEstoqueProdutosActionPerformed(evt);
            }
        });
        menuRelProdutos.add(subMenuRelatorioEstoqueProdutos);

        menuRelatorio.add(menuRelProdutos);

        subMenuRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money.png"))); // NOI18N
        subMenuRelatorioVendas.setText("Vendas");
        subMenuRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioVendasActionPerformed(evt);
            }
        });
        menuRelatorio.add(subMenuRelatorioVendas);

        subMenuRelatorioCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money.png"))); // NOI18N
        subMenuRelatorioCompras.setText("Compras");
        subMenuRelatorioCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioComprasActionPerformed(evt);
            }
        });
        menuRelatorio.add(subMenuRelatorioCompras);

        menuRelCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money.png"))); // NOI18N
        menuRelCaixa.setText("Caixa");

        subMenuRelatorioCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money.png"))); // NOI18N
        subMenuRelatorioCaixa.setText("Caixa Atual");
        subMenuRelatorioCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioCaixaActionPerformed(evt);
            }
        });
        menuRelCaixa.add(subMenuRelatorioCaixa);

        subMenuRelatorioFechamentosCaixas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/money.png"))); // NOI18N
        subMenuRelatorioFechamentosCaixas.setText("Fechamentos de Caixas");
        subMenuRelatorioFechamentosCaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRelatorioFechamentosCaixasActionPerformed(evt);
            }
        });
        menuRelCaixa.add(subMenuRelatorioFechamentosCaixas);

        menuRelatorio.add(menuRelCaixa);

        menuSuperior.add(menuRelatorio);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconsUtils/information.png"))); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        menuSuperior.add(menuSobre);

        setJMenuBar(menuSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        TIMER.cancel();
    }//GEN-LAST:event_formWindowClosing

    private void subMenuCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroUsuariosActionPerformed
        if (FRM_CAD_USUARIO == null)
            FRM_CAD_USUARIO = new FrmCadUsuario();
        FRM_CAD_USUARIO.setINSERIR(true);
        FRM_CAD_USUARIO.setATUALIZAR(true);
        FRM_CAD_USUARIO.setINATIVAR(true);
        FRM_CAD_USUARIO.setCONSULTAR(true);
        FRM_CAD_USUARIO.carregarPermissoes();
        FRM_CAD_USUARIO.setVisible(true);
        
    }//GEN-LAST:event_subMenuCadastroUsuariosActionPerformed

    private void subMenuCadastroCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroCargosActionPerformed
        if (FRM_CAD_CARGO == null)
            FRM_CAD_CARGO = new FrmCadCargo();
        
        FRM_CAD_CARGO.setVisible(true);
       
    }//GEN-LAST:event_subMenuCadastroCargosActionPerformed

    private void subMenuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCategoriasActionPerformed
        if (FRM_CAD_CATEGORIA == null)
            FRM_CAD_CATEGORIA = new FrmCadCategoria();
        FRM_CAD_CATEGORIA.setVisible(true);
    }//GEN-LAST:event_subMenuCategoriasActionPerformed

    private void subMenuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroClientesActionPerformed
        if (FRM_CAD_CLIENTE == null)
            FRM_CAD_CLIENTE = new FrmCadCliente();
        FRM_CAD_CLIENTE.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroClientesActionPerformed

    private void subMenuCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroFuncionariosActionPerformed
        if (FRM_CAD_FUNCIONARIO == null)
            FRM_CAD_FUNCIONARIO = new FrmCadFuncionario();
        FRM_CAD_FUNCIONARIO.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroFuncionariosActionPerformed

    private void subMenuCadastroCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroCidadesActionPerformed
        if (FRM_CAD_CIDADE == null)
            FRM_CAD_CIDADE = new FrmCadCidades();
        FRM_CAD_CIDADE.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroCidadesActionPerformed

    private void subMenuCadastroEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroEstadosActionPerformed
        if (FRM_CAD_ESTADO == null)
            FRM_CAD_ESTADO = new FrmCadEstado();
        FRM_CAD_ESTADO.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroEstadosActionPerformed

    private void subMenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuProdutosActionPerformed
        if (FRM_CAD_PRODUTO == null)
            FRM_CAD_PRODUTO = new FrmCadProduto();
        FRM_CAD_PRODUTO.setVisible(true);
    }//GEN-LAST:event_subMenuProdutosActionPerformed

    private void subMenuCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroFornecedoresActionPerformed
        if (FRM_CAD_FORNECEDOR == null)
            FRM_CAD_FORNECEDOR = new FrmCadFornecedor();
        FRM_CAD_FORNECEDOR.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroFornecedoresActionPerformed

    private void subMenuCadastroComissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroComissoesActionPerformed
        if (FRM_CAD_COMISSOES == null)
            FRM_CAD_COMISSOES = new FrmCadComissoes();
        FRM_CAD_COMISSOES.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroComissoesActionPerformed

    private void subMenuCadastroCondicoesPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroCondicoesPagamentosActionPerformed
       if (FRM_CAD_CONDICAO_PAGAMENTO == null)
            FRM_CAD_CONDICAO_PAGAMENTO = new FrmCadCondicaoPagamento();
        FRM_CAD_CONDICAO_PAGAMENTO.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroCondicoesPagamentosActionPerformed

    private void subMenuCadastroTiposPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCadastroTiposPagamentosActionPerformed
       if (FRM_CAD_TIPO_PAGAMENTO == null)
            FRM_CAD_TIPO_PAGAMENTO = new FrmCadTipoPagamento();
        FRM_CAD_TIPO_PAGAMENTO.setVisible(true);
    }//GEN-LAST:event_subMenuCadastroTiposPagamentosActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        if (INFO == null)
            INFO = new Info();
        INFO.setVisible(true);
    }//GEN-LAST:event_menuSobreMouseClicked

    private void subMenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuComprasActionPerformed
        if (FRM_COMPRAS == null)
            FRM_COMPRAS = new FrmCompras();
        FRM_COMPRAS.setVisible(true);
    }//GEN-LAST:event_subMenuComprasActionPerformed

    private void subMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuVendasActionPerformed
        if (FRM_VENDAS == null)
            FRM_VENDAS = new FrmVendas();
        FRM_VENDAS.setVisible(true);
    }//GEN-LAST:event_subMenuVendasActionPerformed

    private void subMenuCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCaixaActionPerformed
        if (FRM_CAIXA == null)
            FRM_CAIXA = new FrmCaixa();
        FRM_CAIXA.setVisible(true);
    }//GEN-LAST:event_subMenuCaixaActionPerformed

    private void subMenuVisualizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuVisualizarVendasActionPerformed
        if (FRM_VISUALIZAR_VENDAS == null)
            FRM_VISUALIZAR_VENDAS = new FrmVisualizarVendas();
        FRM_VISUALIZAR_VENDAS.setVisible(true);
    }//GEN-LAST:event_subMenuVisualizarVendasActionPerformed

    private void subMenuVisualizarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuVisualizarComprasActionPerformed
        if (FRM_VISUALIZAR_COMPRAS == null)
            FRM_VISUALIZAR_COMPRAS = new FrmVisualizarCompras();
        FRM_VISUALIZAR_COMPRAS.setVisible(true);
    }//GEN-LAST:event_subMenuVisualizarComprasActionPerformed

    private void subMenuRelatorioClientesFisicosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioClientesFisicosAtivosActionPerformed
        try {
            String src = "src/relatorios/rel-clientes-fisicos-ativos.jasper";        
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatorioClientesFisicosAtivosActionPerformed

    private void subMenuRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioVendasActionPerformed
        if (FRM_REL_VENDAS == null)
            FRM_REL_VENDAS = new FrmRelVendas();
        FRM_REL_VENDAS.setVisible(true);
    }//GEN-LAST:event_subMenuRelatorioVendasActionPerformed

    private void subMenuRelatorioClientesJuridicosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioClientesJuridicosAtivosActionPerformed
        try {
            String src = "src/relatorios/rel-clientes-juridicos-ativos.jasper";        
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatorioClientesJuridicosAtivosActionPerformed

    private void subMenuRelatorioProdutosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioProdutosAtivosActionPerformed
        try {
            String src = "src/relatorios/rel-produtos-ativos.jasper";        
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatorioProdutosAtivosActionPerformed

    private void subMenuRelatorioComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioComprasActionPerformed
        if (FRM_REL_COMPRAS == null)
            FRM_REL_COMPRAS = new FrmRelCompras();
        FRM_REL_COMPRAS.setVisible(true);
    }//GEN-LAST:event_subMenuRelatorioComprasActionPerformed

    private void subMenuRelatorioEstoqueProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioEstoqueProdutosActionPerformed
        try {
            String src = "src/relatorios/rel-estoque-produtos.jasper";        
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatorioEstoqueProdutosActionPerformed

    private void subMenuRelatorioCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioCaixaActionPerformed
        try {
            String src = "src/relatorios/rel-caixa.jasper";        
            Caixa caixa = CtrlCaixa.PesquisaUltimoCaixaComTimesTamp();
            Map parametros = new HashMap();
            parametros.put("prDataUltimoFechamentoCaixa", caixa.getAuxFechamentoData());
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src, parametros);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatorioCaixaActionPerformed

    private void subMenuRelatorioFechamentosCaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioFechamentosCaixasActionPerformed
        try {
            String src = "src/relatorios/rel-fechamentos-caixas.jasper";
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatorioFechamentosCaixasActionPerformed

    private void subMenuRelatorioFuncionariosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatorioFuncionariosAtivosActionPerformed
        try { 
            String src = "src/relatorios/rel-funcionarios-ativos.jasper";
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatorioFuncionariosAtivosActionPerformed

    private void subMenuRelatoriosFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRelatoriosFornecedoresActionPerformed
        try {
            String src = "src/relatorios/rel-fornecedores-ativos.jasper";
            JasperViewer view = CtrlRelatorios.gerarRelatorio(src);
            view.setVisible(true);
        } catch(Exception e){
            throw new ExcecaoGenerica(e);
        }
    }//GEN-LAST:event_subMenuRelatoriosFornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windwos".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgPrincipalCenter;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenu menuMovimentacoes;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuRelCaixa;
    private javax.swing.JMenu menuRelClientes;
    private javax.swing.JMenu menuRelProdutos;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuBar menuSuperior;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JMenuItem subMenuCadastroCargos;
    private javax.swing.JMenuItem subMenuCadastroCidades;
    private javax.swing.JMenuItem subMenuCadastroClientes;
    private javax.swing.JMenuItem subMenuCadastroComissoes;
    private javax.swing.JMenuItem subMenuCadastroCondicoesPagamentos;
    private javax.swing.JMenuItem subMenuCadastroEstados;
    private javax.swing.JMenuItem subMenuCadastroFornecedores;
    private javax.swing.JMenuItem subMenuCadastroFuncionarios;
    private javax.swing.JMenuItem subMenuCadastroTiposPagamentos;
    private javax.swing.JMenuItem subMenuCadastroUsuarios;
    private javax.swing.JMenu subMenuCadastrosFinanceiros;
    private javax.swing.JMenuItem subMenuCaixa;
    private javax.swing.JMenuItem subMenuCategorias;
    private javax.swing.JMenuItem subMenuCompras;
    private javax.swing.JMenuItem subMenuProdutos;
    private javax.swing.JMenuItem subMenuRelatorioCaixa;
    private javax.swing.JMenuItem subMenuRelatorioClientesFisicosAtivos;
    private javax.swing.JMenuItem subMenuRelatorioClientesJuridicosAtivos;
    private javax.swing.JMenuItem subMenuRelatorioCompras;
    private javax.swing.JMenuItem subMenuRelatorioEstoqueProdutos;
    private javax.swing.JMenuItem subMenuRelatorioFechamentosCaixas;
    private javax.swing.JMenuItem subMenuRelatorioFuncionariosAtivos;
    private javax.swing.JMenuItem subMenuRelatorioProdutosAtivos;
    private javax.swing.JMenuItem subMenuRelatorioVendas;
    private javax.swing.JMenuItem subMenuRelatoriosFornecedores;
    private javax.swing.JMenuItem subMenuVendas;
    private javax.swing.JMenuItem subMenuVisualizarCompras;
    private javax.swing.JMenuItem subMenuVisualizarVendas;
    // End of variables declaration//GEN-END:variables
}
